#!/bin/sh
basedir=`dirname $0`
jar=${basedir}/dshell.jar
if test ! -f ${jar}
then
    jar=dshell.jar
fi
java -Xbootclasspath/a:${jar} -XX:+TieredCompilation -XX:TieredStopAtLevel=1 dshell.internal.main.DShell $@
exit $?
